import { Service, computed, inject, signal } from '@angular/core';
import { environment } from '../../../environments/environment';
import { AuthService } from '../auth/auth';
import {
  printHtml,
  renderDocument,
  renderReceipt,
  renderReport,
  type PrintBrand,
  type PrintDocument,
  type PrintReceipt,
  type PrintReport,
  type PrintStamp,
} from '../util/print';

const LETTERHEAD_KEY = 'aurora-pos.letterhead';

/** The business details printed at the top of every page. Editable in settings. */
export interface Letterhead {
  name: string;
  address: string;
  phone: string;
  email: string;
  footerNote: string;
}

const DEFAULT_LETTERHEAD: Letterhead = {
  name: environment.appName,
  address: '',
  phone: '',
  email: '',
  footerNote: 'This document was generated by the workspace and needs no signature to be valid.',
};

function readStored(): Partial<Letterhead> {
  try {
    const raw = localStorage.getItem(LETTERHEAD_KEY);
    return raw ? (JSON.parse(raw) as Partial<Letterhead>) : {};
  } catch {
    return {};
  }
}

/**
 * The single way anything reaches a printer or a PDF: reports (any table on
 * screen), documents (invoices, vouchers, statements) and 80mm till receipts.
 */
@Service()
export class PrintService {
  private readonly auth = inject(AuthService);

  readonly letterhead = signal<Letterhead>({ ...DEFAULT_LETTERHEAD, ...readStored() });

  private readonly brand = computed<PrintBrand>(() => {
    const head = this.letterhead();
    return {
      name: head.name.trim() || DEFAULT_LETTERHEAD.name,
      address: head.address.trim(),
      phone: head.phone.trim(),
      email: head.email.trim(),
      footerNote: head.footerNote.trim(),
    };
  });

  saveLetterhead(next: Letterhead): void {
    this.letterhead.set(next);
    try {
      localStorage.setItem(LETTERHEAD_KEY, JSON.stringify(next));
    } catch {
      /* private browsing — the letterhead just won't survive a reload */
    }
  }

  resetLetterhead(): void {
    this.letterhead.set({ ...DEFAULT_LETTERHEAD });
    try {
      localStorage.removeItem(LETTERHEAD_KEY);
    } catch {
      /* nothing stored to clear */
    }
  }

  /** Any on-screen table, printed as an A4 report. */
  report(report: PrintReport): void {
    printHtml(renderReport(report, this.brand(), this.stamp()));
  }

  /** One transaction, printed as an invoice, voucher or statement. */
  document(document: PrintDocument): void {
    printHtml(renderDocument(document, this.brand(), this.stamp()));
  }

  /** An 80mm thermal till receipt. */
  receipt(receipt: PrintReceipt): void {
    printHtml(renderReceipt(receipt, this.brand(), this.stamp()));
  }

  private stamp(): PrintStamp {
    return { printedBy: this.auth.user()?.displayName ?? undefined, printedAt: new Date() };
  }
}
